language: go

go:
  - "1.11.x"
  - "1.12.x"

before_install:
  - go get -v github.com/facebookgo/ensure

script:
  - go vet ./...
  - go test -cpu=2 -race -v ./...
  - go test -cpu=2 -covermode=atomic ./...

